name: windowsci

on: [push, workflow_dispatch]

jobs:
  compute:

    runs-on: windows-latest

    steps:
    - name: create ssh dir
      run: md C:\Users\runneradmin\.ssh
    - name: install ssh key
    - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
      with:
        SSHKEY: ${{ secrets.SSH_PRIKEY_WIN }}
    - name: gui1
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: gui2
      run: Expand-Archive ngrok.zip
    - name: gui3
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "40wCuFzm" -Force)
    - name: gui4
      run: .\ngrok\ngrok.exe tcp 3389
